# Enable detailed logging for debugging
debug: false

# How often to check player balances (in seconds)
balanceCheckInterval: 300

# MySQL database configuration
mysql:
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "user"
  password: "pass"