name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml -DskipTests=true

    - name: Find plugin JAR (excluding original-*)
      id: find_jar
      run: |
        JAR_FILE=$(find target -type f -name "*.jar" ! -name "original-*.jar" | head -n 1)
        echo "jar_file=$JAR_FILE" >> $GITHUB_OUTPUT

    - name: Upload Plugin JAR Only
      uses: actions/upload-artifact@v4
      with:
        name: BalanceTrackerPlugin
        path: ${{ steps.find_jar.outputs.jar_file }}
        retention-days: 5
